spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DEV_DB
    username: kensin
    password: 123
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            # workaround to avoid Hibernate error: https://github.com/pgjdbc/pgjdbc/issues/1102
            non_contextual_creation: true
#    show-sql: true

#logging:
#  # SpringBoot default log is for console, and if you want to print log as file, you need set file config
#   #file: System_Execution.log
#   level:
#    # all classes among package is following mode. eg: debug
#    #nz.co.indepth.infinity: DEBUG
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              # logs the prepared statement parameters
#              BasicBinder: TRACE

